# build environment
FROM node:14.17.3-alpine3.14 as build
WORKDIR /app
COPY package.json ./
COPY yarn.lock ./
RUN yarn --check-files

COPY . /app
RUN yarn run build

# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /app/dist/ /usr/share/nginx/html
COPY  docker/nginx.conf /etc/nginx/conf.d/default.conf
RUN ls -la
EXPOSE 6006
CMD ["nginx", "-g", "daemon off;"]